.TH APT-VENV "1" "apt-venv" "User Commands"
.SH NAME
apt-venv \- apt virtual environment
.SH SYNOPSIS
.TP
\fBapt\-venv\fR [\fB\-D DEBUG\fR] [\fB\-d\fR | \fB\-c COMMAND\fR] release
.TP
\fBapt\-venv\fR -l
.SH DESCRIPTION
\fBapt-venv\fR creates a sort of virtual environments in \fI$HOME/.local/share/apt-venv\fR, one for each release, where \fBapt\fR thinks to be on another distro/release. In these sessions a \fI$APT_VENV\fR variable is set and points out the release name in use.

.SH "OPTIONS"
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.TP
\fB\-D\fR DEBUG, \fB\-\-debug\fR DEBUG
set debug level
.TP
\fB\-v\fR, \fB\-\-version\fR
show program's version number and exit
.TP
\fB\-c\fR COMMAND, \fB\-\-command\fR COMMAND
exec the given \fIcommand\fR instead of entry the
interactive shell
.TP
\fB\-d\fR, \fB\-\-delete\fR
delete venv for release
.TP
\fB\-l\fR, \fB\-\-list\fR
list all venv installed in your system
.TP
\fB\-u\fR, \fB\-\-update\fR
update the apt indexes
.SH
CONFIGURATION FILES
The \fBapt-venv\fR configuration files can be found in \fI$HOME/.config/apt-venv\fR.
