#!/usr/bin/python
from apt_venv import AptVenv, utils, VERSION
from argparse import ArgumentParser

def main():
    parser = ArgumentParser(prog='apt-venv')
    parser.add_argument('-D', '--debug', type=int, help='set debug level')
    parser.add_argument('-v', '--version', action='version', \
        version='%(prog)s ' + VERSION)

    parser.add_argument('-d', '--delete', action="store_true",
        default=False, help="delete venv for distribution")
    parser.add_argument('-c', '--command',
        help="exec the command in venv")
    parser.add_argument('release',
        help="the debian/ubuntu release")

    args = parser.parse_args()

    if args.debug:
        utils.DEBUG_LEVEL = args.debug

    try:
        venv = AptVenv(args.distribution)
        if args.delete:
            venv.delete()
        else:
            venv.run(command=args.command)

    except Exception as exception:
        print (str(exception))
        exit(1)

if __name__ == '__main__':
    main()
